import { Project, ProjectTag, ProjectType } from '@/types/project';

export const projects: Project[] = [
  {
    id: '08347cc0-e16c-49d4-bd10-31ae7c341b52',
    title: 'sakana-san.title',
    description: 'sakana-san.description',
    date: new Date('2025-06-05'),
    type: ProjectType.FREELANCE,
    images: ['/projetcs/sakana-san/sakana-san.webP'],
    videos: ['/projetcs/sakana-san/sakana-san.mp4'],
    tags: [ProjectTag.NEXTJS, ProjectTag.TYPESCRIPT, ProjectTag.TAILWIND],
    slug: 'sakana-san',
    github: 'https://...',
    link: 'https://...',
  },
  {
    id: 'f1b0c2a4-3d8e-4b5c-9f7d-6a0e1f2b3c4d',
    title: 'romane-faupin.title',
    description: 'romane-faupin.description',
    date: new Date('2024-03-08'),
    type: ProjectType.PERSONAL,
    images: ['/projetcs/romane-faupin/romane-faupin.webP'],
    videos: ['/projetcs/romane-faupin/romane-faupin.mp4'],
    slug: 'romane-faupin',
  },
  {
    id: 'a1b2c3d4-e5f6-7g8h-9i0j-k1l2m3n4o5p6',
    title: 'kerluskellik.title',
    description: 'kerluskellik.description',
    date: new Date('2025-05-05'),
    type: ProjectType.TRAVEL,
    images: ['/projetcs/kerluskellik/kerluskellik.webP'],
    videos: ['/projetcs/kerluskellik/kerluskellik.mp4'],
    slug: 'kerluskellik',
  },
  {
    id: 'a49566dd-24bd-4031-9119-dc87d2c390e3',
    title: 'fast-foodie.title',
    description: 'fast-foodie.description',
    date: new Date('2025-05-05'),
    type: ProjectType.FREELANCE,
    images: [
      '/projetcs/fast-foodie/fast-foodie.webP',
      '/projetcs/romane-faupin/romane-faupin.webP',
      '/projetcs/kerluskellik/kerluskellik.webP',
      '/projetcs/sakana-san/sakana-san.webP',
      '/projetcs/kerluskellik/kerluskellik.webP',
      '/projetcs/fast-foodie/fast-foodie.webP',
    ],
    videos: ['/projetcs/fast-foodie/fast-foodie.mp4'],
    tags: [ProjectTag.NEXTJS, ProjectTag.TYPESCRIPT, ProjectTag.TAILWIND],
    slug: 'fast-foodie',
    github: 'https://...',
    link: 'https://...',
    customerUrl: 'https://...',
  },
  {
    id: '74579a27-185d-488d-a5fa-1585b2531d4b',
    title: 'romane-faupin.title',
    description: 'romane-faupin.description',
    date: new Date('2025-05-05'),
    type: ProjectType.PERSONAL,
    images: ['/projetcs/romane-faupin/romane-faupin.webP'],
    videos: ['/projetcs/romane-faupin/romane-faupin.mp4'],
    slug: 'romane-faupin',
  },
];
